### ISSUE TITLE
Research NZMS

### ISSUE THREAD

**Issue by kechinn** [kechinn/WSDOT-ESO#6]
Partial test issue:) @jesse-WSDOT Need to do some research on updating NZMS metadata and location in GIS Workbench. This item will probably move to SharePoint.

**Comment by jesse-WSDOT** [comment]
NZMS will need to be moved to the **environmental business area**. Currently the NSMZ is under Environmental Heath in the RMEC GeoPortal.  This might be a good place on the workbench.  Another option might be F&W. Metadata will need to be updated to show new data steward as ESO.  Created task in SharePoint to complete by July 31st.  

![SnipWBNSMS](https://user-images.githubusercontent.com/52254628/60224626-15a16500-9838-11e9-85b9-1782263ed8c4.JPG)

**Comment by jesse-WSDOT** [comment]
Sent DBA request to add read/write permission to 17P databases.  With edit role on ESO_EnviDataEditon17P.
